name: 🚀 Deploy Laravel via FTP

on:
  push:
    branches:
      - main  # atau branch production kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2  # sesuaikan dengan versi PHP yang kamu pakai
          extensions: mbstring, bcmath, curl, fileinfo, intl, openssl, pdo, tokenizer, xml

      - name: Install Dependencies (Composer)
        run: composer install --no-dev --optimize-autoloader

      - name: Upload Laravel to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "/htdocs/" # sesuaikan dengan folder di hosting
          local-dir: "./"             # upload semua file project (bisa difilter)
